### ISSUE TITLE
Missing java script

### ISSUE THREAD

**Issue by HerrNilZon** [lady-segfault/caribon#1]
Dear lise-henry,

thanks a lot for this great tool. Its exactly what I was looking for.

But I see that in the current head revision, the java script is not enabled. For me, the command
`./target/release/caribon --language=english --input=README.md --output=example.html --fuzzy=0.5`

produces a html file, whose head reads

```
<html><head><br/>
<meta charset = "UTF-8"><br/>
<script><br/>
    function on(name) {<br/>
        var elements = document.getElementsByClassName(name);<br/>
        for (var i = 0; i < elements.length; i++) {<br/>
            var elem = elements[i];<br/>
            elem.style.backgroundColor = "pink";<br/>
        }<br/>
    }<br/>
    function off(name) {<br/>
        var elements = document.getElementsByClassName(name);<br/>
        for (var i = 0; i < elements.length; i++) {<br/>
            var elem = elements[i];<br/>
            elem.style.backgroundColor = "white";<br/>
        }<br/>
    }<br/>
</script><br/>
<br/>
</head><br/>

```

Accordingly, the repetition pair don't get highlighted in the browser.

Am I missing something?

Best

Nils

**Comment by crowdagger** [comment]
Thanks for submitting this issue! (and sorry for the delay answering to it)

The problem was the "<br />" in the head document, which occurred when input format was set to text. This should now be fixed. The javascript in itself is quite minimal but is normally enough to highligh repetitions when you mouseover them.
